project:
  type: website

website:
  title: "32_Step_Ahead_Solutions"
  navbar:
    left: 
      - text: Proposal
        menu: 
          - text: Our Proposal
            href: "Proposal/fyp_proposal.html"
          
      - text: Initial Research  
        menu: 
          - text: On-the-ground Research
            href: "Initial_Research/On-the-ground_Research.html"
            menu: 
              - text: Ang Mo Kio
                href: "Initial_Research/AMK.html"
              - text: Punggol
                href: "Initial_Research/PG.html"
          - text: Literature Review
            href: "Initial_Research/literature_review.html"
            
      - text: Data Exploration
        menu: 
          - text: BA
            href: "Data Exploration/"
          - text: SMT
            href: "Data Exploration/"
          
      - text: Analysis 
        menu: 
          - text: Demographics Analysis
            href: "Analysis/Demographic Analysis/demo.html"
          - text: Geospatial Analysis
            href: "Analysis/Geographic Analysis/Geographic-Analysis.html"
    
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About us 

format:
  html:
    theme: lumen
    css: styles.css
    toc: true

editor: visual

